version: '3.8'
services:
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local